# Generated by Django 4.1.5 on 2023-08-02 20:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('percentage', models.IntegerField()),
                ('da_percentage', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('is_fixed', models.BooleanField(default=False)),
                ('is_dcpc', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('percentage', models.IntegerField()),
                ('da_percentage', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('is_fixed', models.BooleanField(default=False)),
                ('is_dcpc', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='department_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='emp_classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='employee_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='grade_pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='grade_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='miscellaneous_deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='pay_scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=120)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.bank')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('middle_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('taluka', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('pin_code', models.IntegerField()),
                ('adhar_card', models.CharField(max_length=120, unique=True)),
                ('pan_card', models.CharField(max_length=120, unique=True)),
                ('biometric_no', models.CharField(max_length=120, unique=True)),
                ('nps_dcps', models.CharField(max_length=120, unique=True)),
                ('department', models.CharField(max_length=120, unique=True)),
                ('hra', models.BooleanField(default=False)),
                ('ta', models.BooleanField(default=False)),
                ('da', models.BooleanField(default=False)),
                ('physical_disable', models.BooleanField(default=False)),
                ('basic_salary', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('date_of_retirement', models.DateField(default=datetime.datetime(2023, 8, 3, 2, 7, 8, 329819))),
                ('bank_ac_no', models.IntegerField()),
                ('permanent_address', models.CharField(max_length=120, unique=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.designation')),
                ('employee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.employee_type')),
                ('grade_pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.grade_pay')),
                ('grade_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.grade_payment')),
                ('pay_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.pay_scale')),
            ],
        ),
    ]
