# Generated by Django 4.1.5 on 2023-08-03 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_employee_address_alter_employee_adhar_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_retirement',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 3, 16, 21, 0, 524657), null=True),
        ),
    ]
