# Generated by Django 4.1.5 on 2023-08-03 11:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_employee_date_of_retirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_retirement',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 3, 16, 39, 24, 403267), null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.department_type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nps_dcps',
            field=models.CharField(blank=True, choices=[('1', 'NPS'), ('2', 'DCPS')], max_length=120, null=True),
        ),
    ]
