# Generated by Django 4.1.5 on 2023-08-03 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_employee_date_of_retirement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='state',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_retirement',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 3, 16, 45, 17, 462398), null=True),
        ),
    ]
