# Generated by Django 4.1.5 on 2023-08-03 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_employee_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_retirement',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 3, 16, 46, 35, 973847), null=True),
        ),
    ]
