# Generated by Django 4.1.5 on 2023-08-07 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_employee_basic_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_retirement',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 0, 39, 39, 293137), null=True),
        ),
    ]
