# Generated by Django 4.1.5 on 2023-08-07 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_employee_date_of_retirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dearness_allowance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='house_rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='travel_allowance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='washing_clothes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_retirement',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 1, 49, 19, 119019), null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nps_dcps',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
