# Generated by Django 4.1.5 on 2023-08-07 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_employee_dearness_allowance_employee_house_rent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dearness_allowance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='house_rent',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='travel_allowance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='washing_clothes',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_retirement',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 4, 7, 59, 660363), null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nps_dcps',
            field=models.CharField(blank=True, choices=[('1', 'NPS'), ('2', 'DCPS')], max_length=120, null=True),
        ),
    ]
