# Generated by Django 4.1.5 on 2023-08-09 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_allowance_amount_alter_allowance_da_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='da_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_retirement',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 9, 14, 34, 37, 320937), null=True),
        ),
    ]
