# Generated by Django 4.1.5 on 2023-08-09 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_employee_da_alter_employee_date_of_retirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='da',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_retirement',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 9, 16, 33, 34, 28739), null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hra',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='physical_disable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ta',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
