# Generated by Django 4.1.5 on 2023-08-09 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_employee_courtesy_titles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_retirement',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 10, 1, 56, 37, 584378), null=True),
        ),
    ]
