# Generated by Django 4.1.5 on 2023-08-10 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_alter_allowance_is_dcpc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='is_fixed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='is_fixed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_retirement',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 11, 2, 11, 21, 44934), null=True),
        ),
    ]
