# Generated by Django 4.1.5 on 2023-08-13 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_alter_employee_date_of_joining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='adhar_card',
            field=models.IntegerField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_retirement',
            field=models.DateField(default=datetime.datetime(2023, 8, 13, 22, 28, 11, 515036)),
        ),
    ]
