# Generated by Django 4.1.5 on 2023-08-14 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_alter_employee_date_of_retirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_retirement',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 15, 54, 23, 627086)),
        ),
    ]
