# Generated by Django 4.1.5 on 2023-08-15 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_alter_employee_date_of_retirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dcps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_retirement',
            field=models.DateField(default=datetime.datetime(2023, 8, 15, 6, 6, 9, 994081)),
        ),
    ]
