# Generated by Django 4.1.5 on 2023-08-17 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_alter_employee_date_of_retirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=120),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=120),
        ),
        migrations.AlterField(
            model_name='department_type',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=120),
        ),
        migrations.AlterField(
            model_name='designation',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=120),
        ),
        migrations.AlterField(
            model_name='emp_classes',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=120),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_retirement',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 5, 42, 30, 46371)),
        ),
        migrations.AlterField(
            model_name='employee_type',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade_pay',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade_payment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=120),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=120),
        ),
        migrations.AlterField(
            model_name='miscellaneous_deduction',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=120),
        ),
        migrations.AlterField(
            model_name='pay_scale',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=120),
        ),
    ]
