# Generated by Django 4.1.5 on 2023-08-17 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_alter_allowance_status_alter_bank_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_retirement',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 5, 48, 15, 773905)),
        ),
    ]
