# Generated by Django 4.1.5 on 2023-08-19 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0073_alter_employee_date_of_retirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_retirement',
            field=models.DateField(default=datetime.datetime(2023, 8, 19, 8, 52, 48, 810912)),
        ),
        migrations.AlterField(
            model_name='miscellaneous_deduction',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
