# Generated by Django 4.1.5 on 2023-08-26 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0079_alter_employee_date_of_retirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_retirement',
            field=models.DateField(default=datetime.datetime(2023, 8, 26, 13, 7, 5, 138561)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dcps',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
