# Generated by Django 4.1.5 on 2023-08-02 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_miscellaneous_deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('description', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=120)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.employee')),
                ('miscellaneous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.miscellaneous_deduction')),
            ],
        ),
        migrations.CreateModel(
            name='employee_loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_loan_amount', models.BigIntegerField()),
                ('loan_percentage', models.BigIntegerField()),
                ('year', models.BigIntegerField()),
                ('emi', models.BigIntegerField()),
                ('description', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=120)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.employee')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.loan')),
            ],
        ),
        migrations.CreateModel(
            name='employee_deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('description', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=120)),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.deduction')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.employee')),
            ],
        ),
        migrations.CreateModel(
            name='employee_allowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('description', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=120)),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.allowance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.employee')),
            ],
        ),
    ]
