# Generated by Django 4.1.5 on 2023-08-03 10:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_employee_date_of_retirement'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_department_transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incerement_date', models.DateField(blank=True, default=datetime.datetime(2023, 8, 3, 16, 21, 0, 534300), null=True)),
                ('description', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=120)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsdss', to='store.employee')),
                ('new_deparment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dfdfdffs', to='store.department_type')),
                ('old_deparment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsdsd', to='store.department_type')),
            ],
        ),
    ]
