# Generated by Django 4.1.5 on 2023-08-03 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_employee_department_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 3, 16, 39, 24, 408268), null=True),
        ),
    ]
