# Generated by Django 4.1.5 on 2023-08-03 12:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_employee_date_of_retirement'),
        ('transactions', '0010_alter_employee_department_transfer_incerement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 3, 18, 9, 34, 292828), null=True),
        ),
        migrations.CreateModel(
            name='vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('no_of_vacancy', models.BigIntegerField()),
                ('description', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=120)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.department_type')),
            ],
        ),
    ]
