# Generated by Django 4.1.5 on 2023-08-03 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_remove_employee_department_transfer_incerement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 3, 20, 57, 38, 109729), null=True),
        ),
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 3, 20, 57, 38, 108729), null=True),
        ),
    ]
