# Generated by Django 4.1.5 on 2023-08-04 16:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_employee_date_of_retirement'),
        ('transactions', '0014_alter_employee_department_transfer_transfer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 4, 22, 1, 20, 482396), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 4, 22, 1, 20, 484354), null=True),
        ),
        migrations.CreateModel(
            name='leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, default=datetime.datetime(2023, 8, 4, 22, 1, 20, 486365), null=True)),
                ('date_to', models.DateField(blank=True, default=datetime.datetime(2023, 8, 4, 22, 1, 20, 486365), null=True)),
                ('total_days', models.IntegerField()),
                ('description', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=120)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.employee')),
            ],
        ),
    ]
