# Generated by Django 4.1.5 on 2023-08-06 19:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_employee_date_of_retirement'),
        ('transactions', '0015_alter_employee_department_transfer_transfer_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_deduction',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_deduction',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 7, 1, 21, 17, 838010), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 7, 1, 21, 17, 840019), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 7, 1, 21, 17, 840019), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 7, 1, 21, 17, 840019), null=True),
        ),
        migrations.CreateModel(
            name='employee_salary_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_salary_generated', models.BooleanField()),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.department_type')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.employee')),
            ],
        ),
    ]
