# Generated by Django 4.1.5 on 2023-08-06 20:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_employee_date_of_retirement'),
        ('transactions', '0016_employee_deduction_month_employee_deduction_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_salary_generated', models.BooleanField()),
                ('salary_date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.department_type')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.employee')),
            ],
        ),
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 7, 1, 54, 53, 657006), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 7, 1, 54, 53, 658005), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 7, 1, 54, 53, 658005), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 7, 1, 54, 53, 658005), null=True),
        ),
        migrations.DeleteModel(
            name='employee_salary_history',
        ),
    ]
