# Generated by Django 4.1.5 on 2023-08-06 20:56

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_employee_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_deduction',
            name='month',
        ),
        migrations.RemoveField(
            model_name='employee_deduction',
            name='year',
        ),
        migrations.AddField(
            model_name='employee_deduction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 7, 2, 26, 24, 295407), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 7, 2, 26, 24, 296348), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 7, 2, 26, 24, 296348), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 7, 2, 26, 24, 296348), null=True),
        ),
    ]
