# Generated by Django 4.1.5 on 2023-08-07 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_remove_employee_deduction_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 7, 23, 1, 31, 760863), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 7, 23, 1, 31, 762406), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='new_basic',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='old_basic',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 7, 23, 1, 31, 762406), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 7, 23, 1, 31, 762406), null=True),
        ),
    ]
