# Generated by Django 4.1.5 on 2023-08-07 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_alter_employee_department_transfer_transfer_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_allowance',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='employee_deduction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='employee_miscellaneous_deduction',
            name='amount',
        ),
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 0, 39, 39, 306302), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 0, 39, 39, 307299), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 0, 39, 39, 308300), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 0, 39, 39, 308300), null=True),
        ),
    ]
