# Generated by Django 4.1.5 on 2023-08-07 19:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_employee_date_of_retirement'),
        ('transactions', '0021_remove_employee_allowance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_allowance',
            name='allowance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_allo', to='store.allowance'),
        ),
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 0, 58, 49, 940694), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 0, 58, 49, 941729), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 0, 58, 49, 942728), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 0, 58, 49, 942728), null=True),
        ),
    ]
