# Generated by Django 4.1.5 on 2023-08-07 19:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_employee_date_of_retirement'),
        ('transactions', '0022_alter_employee_allowance_allowance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_allowance',
            name='allowance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.allowance'),
        ),
        migrations.AlterField(
            model_name='employee_allowance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_allo', to='store.employee'),
        ),
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 1, 1, 8, 709458), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 1, 1, 8, 711459), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 1, 1, 8, 711459), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 1, 1, 8, 711459), null=True),
        ),
    ]
