# Generated by Django 4.1.5 on 2023-08-07 22:54

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_alter_employee_department_transfer_transfer_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_deduction',
            name='date',
        ),
        migrations.AddField(
            model_name='employee_miscellaneous_deduction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 4, 24, 40, 732984), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 4, 24, 40, 733981), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 4, 24, 40, 733981), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 4, 24, 40, 733981), null=True),
        ),
    ]
