# Generated by Django 4.1.5 on 2023-08-07 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0029_alter_employee_department_transfer_transfer_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_salary',
            name='allowance_amount',
            field=models.FloatField(default=34343),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='deduction_amount',
            field=models.FloatField(default=343434),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='loan_amount',
            field=models.FloatField(default=343434),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='miscellaneous_deduction_amount',
            field=models.FloatField(default=34343),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='total_salary',
            field=models.FloatField(default=43434),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 5, 2, 33, 736074), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 5, 2, 33, 737075), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 5, 2, 33, 738070), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 8, 5, 2, 33, 738070), null=True),
        ),
    ]
