# Generated by Django 4.1.5 on 2023-08-17 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0061_employee_allowance_amount_employee_deduction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_allowance',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=120),
        ),
        migrations.AlterField(
            model_name='employee_deduction',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=120),
        ),
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=120),
        ),
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 5, 42, 30, 58310), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 5, 42, 30, 58310), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=120),
        ),
        migrations.AlterField(
            model_name='employee_loan',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=120),
        ),
        migrations.AlterField(
            model_name='employee_miscellaneous_deduction',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=120),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 5, 42, 30, 64870), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 5, 42, 30, 64870), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=120),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=120),
        ),
    ]
