# Generated by Django 4.1.5 on 2023-08-17 00:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_alter_employee_date_of_retirement'),
        ('transactions', '0065_alter_employee_department_transfer_transfer_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='month_working_days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 6, 7, 15, 778711), null=True)),
                ('working_days', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='employee_total_leaves',
            old_name='working_days',
            new_name='earned_leaves',
        ),
        migrations.RemoveField(
            model_name='employee_total_leaves',
            name='date',
        ),
        migrations.AddField(
            model_name='employee_total_leaves',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_total_leaves',
            name='medical_leaves',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 6, 7, 15, 758806), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 6, 7, 15, 758806), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 6, 7, 15, 758806), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 6, 7, 15, 758806), null=True),
        ),
    ]
