# Generated by Django 4.1.5 on 2023-08-17 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0066_month_working_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 6, 7, 40, 662996), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 6, 7, 40, 662996), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 6, 7, 40, 662996), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 6, 7, 40, 662996), null=True),
        ),
        migrations.AlterField(
            model_name='month_working_days',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 6, 7, 40, 686138), null=True),
        ),
    ]
