# Generated by Django 4.1.5 on 2023-08-17 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0068_alter_employee_department_transfer_transfer_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='leave_type',
            field=models.CharField(choices=[('medical leave', 'Medical Leave'), ('earned leave', 'Earned Leave')], default='medical leave', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 9, 6, 34, 551188), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 9, 6, 34, 558293), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 9, 6, 34, 581045), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 9, 6, 34, 581045), null=True),
        ),
        migrations.AlterField(
            model_name='month_working_days',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 9, 6, 34, 581045), null=True),
        ),
    ]
