# Generated by Django 4.1.5 on 2023-08-17 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0069_leaves_leave_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_total_leaves',
            name='marriage_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee_total_leaves',
            name='paternity_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 10, 45, 52, 572506), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 10, 45, 52, 572506), null=True),
        ),
        migrations.AlterField(
            model_name='employee_total_leaves',
            name='earned_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee_total_leaves',
            name='medical_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 10, 45, 52, 572506), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 10, 45, 52, 572506), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='leave_type',
            field=models.CharField(choices=[('medical_leave', 'Medical Leave'), ('earned_leave', 'Earned Leave'), ('marriage_leave', 'Marriage Leave'), ('paternity_leave', 'Paternity Leave')], max_length=120),
        ),
        migrations.AlterField(
            model_name='month_working_days',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 17, 10, 45, 52, 587094), null=True),
        ),
    ]
