# Generated by Django 4.1.5 on 2023-08-19 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0073_alter_employee_allowance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_loan',
            name='loan_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 9, 23, 24, 459262), null=True),
        ),
        migrations.AddField(
            model_name='employee_loan',
            name='loan_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 9, 23, 24, 459262), null=True),
        ),
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 9, 23, 24, 461260), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 9, 23, 24, 462280), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 9, 23, 24, 462280), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 9, 23, 24, 462280), null=True),
        ),
        migrations.AlterField(
            model_name='month_working_days',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 9, 23, 24, 476576), null=True),
        ),
    ]
