# Generated by Django 4.1.5 on 2023-08-19 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0074_employee_loan_loan_from_employee_loan_loan_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 9, 38, 1, 645585), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 9, 38, 1, 646585), null=True),
        ),
        migrations.AlterField(
            model_name='employee_loan',
            name='loan_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 9, 38, 1, 643584), null=True),
        ),
        migrations.AlterField(
            model_name='employee_loan',
            name='loan_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 9, 38, 1, 643584), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 9, 38, 1, 647585), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 9, 38, 1, 647585), null=True),
        ),
        migrations.AlterField(
            model_name='month_working_days',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 9, 38, 1, 664632), null=True),
        ),
    ]
