# Generated by Django 4.1.5 on 2023-08-19 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0075_alter_employee_department_transfer_transfer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 13, 5, 54, 948110), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 13, 5, 54, 950045), null=True),
        ),
        migrations.AlterField(
            model_name='employee_loan',
            name='loan_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 13, 5, 54, 945529), null=True),
        ),
        migrations.AlterField(
            model_name='employee_loan',
            name='loan_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 13, 5, 54, 945529), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 13, 5, 54, 950045), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 13, 5, 54, 950045), null=True),
        ),
        migrations.AlterField(
            model_name='month_working_days',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 19, 13, 5, 54, 969098), null=True),
        ),
    ]
