# Generated by Django 4.1.5 on 2023-08-25 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0076_alter_employee_department_transfer_transfer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 25, 23, 38, 9, 675330), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 25, 23, 38, 9, 676219), null=True),
        ),
        migrations.AlterField(
            model_name='employee_loan',
            name='loan_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 25, 23, 38, 9, 673707), null=True),
        ),
        migrations.AlterField(
            model_name='employee_loan',
            name='loan_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 25, 23, 38, 9, 673707), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 25, 23, 38, 9, 676219), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 25, 23, 38, 9, 677218), null=True),
        ),
        migrations.AlterField(
            model_name='month_working_days',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 25, 23, 38, 9, 688738), null=True),
        ),
    ]
