# Generated by Django 4.1.5 on 2023-08-26 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0077_alter_employee_department_transfer_transfer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_department_transfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 26, 13, 7, 5, 148637), null=True),
        ),
        migrations.AlterField(
            model_name='employee_increament',
            name='incerement_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 26, 13, 7, 5, 150676), null=True),
        ),
        migrations.AlterField(
            model_name='employee_loan',
            name='loan_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 26, 13, 7, 5, 144636), null=True),
        ),
        migrations.AlterField(
            model_name='employee_loan',
            name='loan_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 26, 13, 7, 5, 144636), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 26, 13, 7, 5, 150676), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 26, 13, 7, 5, 150676), null=True),
        ),
        migrations.AlterField(
            model_name='month_working_days',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 26, 13, 7, 5, 168557), null=True),
        ),
    ]
